### ISSUE TITLE
No barcodes in output

### ISSUE THREAD

**Issue by heathergeiger** [CHPGenetics/GMM-demux#3]
We are currently testing a nuclei hashing protocol. Data for this is attached. These are nUMI counts per sample for 8 different sample tags. These results come from running CellRanger with feature barcoding option, and then extracting the counts just for the antibody portion into a CSV file. So this file includes only cell barcodes determined to be real cells (based on having sufficient RNA) according to CellRanger.

The file is attached with suffix ".txt" as Github requires, but was originally named mouse_tissue_mix_with_feature_barcoding_HTO_counts.csv.

I am getting an empty output for SSD_mtx/barcodes.tsv.gz after run the following command.

```
GMM-demux -c mouse_tissue_mix_with_feature_barcoding_HTO_counts.csv tag1,tag2,tag3,tag4,tag5,tag6,tag7,tag8
```

Any idea why this might be happening?

We realize this data was not the best quality. We are expecting a relatively high rate of cells that cannot be assigned to any particular sample.

Nonetheless we are getting over 11,000 cells called as singlets according to Seurat HTODemux run on the same counts. So we would expect at least some SSDs rather than 0.

I even tried decreasing the confidence threshold extremely low (to 0.1). This gives some SSD barcodes, but still very few ( a bit over 4000). 

[mouse_tissue_mix_with_feature_barcoding_HTO_counts_csv.txt](https://github.com/CHPGenetics/GMM-Demux/files/5197918/mouse_tissue_mix_with_feature_barcoding_HTO_counts_csv.txt)

**Comment by xhongyi** [comment]
Got it. Will take a look this weekend!

Hongyi

**Comment by xhongyi** [comment]
Sorry for taking so long to answer your question.

I did some plotting of the distribution of your data. The hto distributions look like these:

![image](https://user-images.githubusercontent.com/4156276/103479665-42114680-4e0a-11eb-8a77-08a49f0aaa51.png)
![image](https://user-images.githubusercontent.com/4156276/103479673-4c334500-4e0a-11eb-991b-e0480561dac5.png)
![image](https://user-images.githubusercontent.com/4156276/103479680-52292600-4e0a-11eb-8f5a-b79611a9eaad.png)
![image](https://user-images.githubusercontent.com/4156276/103479688-610fd880-4e0a-11eb-8a46-b78547af8625.png)

The two Gaussian peaks share a great portion of overlaps. Our hto distributions have more well defined Gaussian peaks:

![image](https://user-images.githubusercontent.com/4156276/103479718-90bee080-4e0a-11eb-9d3d-704553b60b23.png)

There could be multiple causes that result in not well defined Gaussian features in the distributions.
Most likely, this is because the antibody concentration difference, before and after pooling, isn't significant enough.
I would suggest significantly diluting the sample-cell-and-antibody mixture solution right before pooling, to ensure that there will be a significant drop in antibody concentration so that in the antibody distributions, there will be clearly defined gaps between Gaussian peaks.

Back to your original question. Your case likely falls to the limitations of GMM-Demux: GMM-Demux requires well-defined Gaussian features in the data distribution, which your data lacks.

In this case, I would recommend you use Seurat. Seurat uses a K-medoid-based method, which does not presume any distributions of the dataset. When using Seurat, I would recommend you pay special attention to the t_l threshold and tune it to reflect your experiment settings.
