### ISSUE TITLE
Two-sided cutoff in the HTO classification?

### ISSUE THREAD

**Issue by fnakaki** [CHPGenetics/GMM-demux#7]
Hi, I'm using GMM-Demux for the classification of HTO-labeled samples in multiplexed scRNA-seq, and it works quite well. However, when I demultiplexed the pooled library with only 2 samples (-t 0.8), I found GMM-demux called the cells with very low HTO counts also "positive", and I suspect this is because GMM-Demux made a cutoff of both sides of the standard curve:
![Barcode UMI scatter plot](https://user-images.githubusercontent.com/36917399/203085896-e28ef00a-c88e-411a-bf1f-d85ec6f68b2c.png)
This is a log-scale scatter plot of HTO counts. As you see, for example, the doublets (id 2) have spread on both sides, though one of them (the lower part) should be singlets. And some of the very negative cells are called singlets, too.
How can I make it one-sided to label them correctly? Thank you!

**Comment by xhongyi** [comment]
Hi fnakaki,

Thanks for reporting this issue! I think this rises from GMM-Demux assigning classifications based by likelihood and it is perhaps due to that the "positive" distribution is perhaps a bit too "flat" and the "negative" distribution being too "pointy" and that masses up the classifications for droplets with too small values.

I'm not sure if it is possible for you share your data with me so I can further look into this matter. I only need the HTO data and you can send it to me in mtx format via hongyi.xin@sjtu.edu.cn (it would be great if you can format the title to "[GMM-Demux Issue]xxx").

I am sorry for the inconvenience but for now I suggest trimming the cells with too low HTO counts.

Thanks,
Hongyi

**Comment by fnakaki** [comment]
Thanks Hongyi, I'll send you the matrix privately for your further investigation. Let me know if you have any updates!

**Comment by xhongyi** [comment]
Hi fnakaki,

I'm not sure if this issue has been resolved. If it has, I will close the issue.

If not, please let me know.

Hongyi

**Comment by fnakaki** [comment]
Hi Hongyi, the lower part is correctly assigned as negative with v0.2.2.1. Thanks!

**Comment by xhongyi** [comment]
> Hi Hongyi, the lower part is correctly assigned as negative with v0.2.2.1. Thanks!

Thanks fnakaki!
